name: 'github_health_analytics'
version: '1.0.0'
config-version: 2

profile: 'bq_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  github_health_analytics:
    +on_schema_change: sync_all_columns
    staging:
      +materialized: view
    intermediate:
      +materialized: incremental
      +incremental_strategy: merge
    marts:
      +materialized: table

snapshots:
  github_health_analytics:
    +target_schema: snapshots

vars:
  raw_payload_col: "payload"
  raw_ingested_at_col: "ingestion_date"
  stale_days: 30
