FROM apache/airflow:2.8.1

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir "apache-airflow==2.8.1" apache-airflow-providers-google --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.8.1/constraints-3.8.txt"
RUN pip install --no-cache-dir google-cloud-storage google-cloud-bigquery requests "dbt-bigquery~=1.7.0"
